This is initial code...
This is initial code...
This is initial code...
This is initial code...
This is initial code...
This is initial code...
This is initial code...
This is initial code...
This is Feature2 code...
This is initial code...
Some updates on master...
This is Feature_2 code...
Fixing few things on Feature_2 branch... :)
Editing something dirctly on github... 

This is Featur 4 code...
This is Feature_4 code...